### PR TITLE
allowing configurable helm_command

### PR DESCRIPTION
**Pull request by nmaki**
Changed the logic so that specifying the helm_command allows more control over the action the plugin will take. This allows customization of what happens on different build events such as doing a dry run on a pull_request.

i.e. explicitly specifying 'upgrade' for the helm_command will result in plugin building out the upgrade command as it normally would.

If no helm_command is specified it should fall back on the old behavior of deciding what to do from the build event so this shouldn't break existing builds.

### CODE REVIEW

**Comment by ipedrazas** [comment]
Not sure I understand this change. If we change this, all the plugins using a string slice will break. I have to look at it a little bit deeper.

**Comment by nmaki** [comment]
I might be missing something about how it works but it looks to me that the plugin currently is not using the helm_command from the input at all as it overwrites whatever that value might be when it runs through setHelmCommand. So I guess someone could be currently passing an array into that value, but it doe not appear to be taking any effect on how the plugin evaluates currently.

Ultimately the goal was to be able to run the different helm commands 'upgrade' and 'delete' irrespective of the DRONE_BUILD_EVENT environment variable.

**Comment by rmoshea** [comment]
Being able to do upgrade dry runs on pull requests would be nice 👍

**Comment by jmccann** [comment]
@ipedrazas Any thoughts on the above comment https://github.com/ipedrazas/drone-helm/pull/43#issuecomment-324937864 ?

We are also looking to be able to run an `upgrade` or `delete` commands on events outside `delete`.

Wouldn't mind contributing something!

**Comment by ipedrazas** [comment]
merged 😄

**Pull request merged**
