### PR TITLE
Glide and Canary image support

### PR DESCRIPTION
**Pull request by alexei-led**
Hello, Ivan

I would suggest few changes to this project, some are related to build/dev env plus one small feature:

1. use glide for Go dependency management
2. vendor project dependencies (keep them in Git - reduce dependency on GitHub)
3. use Docker multi-stage build to be able to build anywhere w/out installing Go
4. add `--canary-image` flag to support Helm canary release (sometimes bug fixes are already committed, but Helm is not released yet)

### CODE REVIEW

**Comment by ipedrazas** [comment]
Wow! that's a big improvement. Do we need the vendor directory? I guess if we don't include it, we will need to add glide on the go image that does the build, right?

I'll review it later when I'm on my laptop but it looks very good! Thanks! 🙌

**Comment by alexei-led** [comment]
When I've just started to use `glide`, I've used it as Node.js `project.json` file: meaning importing all dependencies on every build machine. But Go works differently. 
While it's possible to import all missing packages using `glide` commands every time you are running in the clean environment (or running a new CI build), I think it's better to bring all required package files together with app source, to avoid unexpected failures and get faster and repeatable builds. Go needs all files to compile anyway, so why not to bring them with `git pull/clone`? 
Then I'm using `glide` from time to time, just to update dependencies or to add/remove some package.

**Comment by hokichaio** [comment]
Hi, I think I bump into this issue by using the latest commit
https://github.com/ipedrazas/drone-helm/issues/36

looks like the container doesn't have CA certificates?

**Comment by alexei-led** [comment]
@hokichaio added ca_certificates Alpine package

**Comment by hokichaio** [comment]
@alexei-led thanks for fixing. confirmed it's working perfectly now 👍

**Comment by ipedrazas** [comment]
Let's merge, then!

**Pull request merged**
